wheel_size: 275
wheel_hole_size: 100
slice_padding: 5
slice_border_width: 3
font:
wheel_to_wheel_delay: 10
single_press_shortcut: ctrl+c
single_press_wheel: default
double_press_shortcut: press ctrl+v
double_press_wheel: default

colors:
  red: 0xab4642

palettes:
  rainbow:
    - red
    - 0xdc9656
    - 0xf7ca88
    - 0xa1b56c
    - 0x86c1b9
    - 0x7cafc2
    - 0xba8baf
    - 0xa16946

# action groups?
# reuse actions?

wheels:
  - name: default
    palette: rainbow
    options:
      - name: Copy
        action: press meta+c

      - name: Cut
        action: press meta+x

      - name: Paste
        action: press meta+v

      - name: Four
        action: press ctrl+v

      - name: Five
        action: press ctrl+v

      - name: Six
        action: press ctrl+v

      - name: Seven
        action: press ctrl+v

      - name: Eight
        action: press ctrl+v

      - name: New Layer
        action: press meta+c

      - name: Delete Layer
        action: press meta+x

      - name: Duplicate Layer
        action: press meta+v

      - name: New File
        action: press meta+v

  - name: qtcreate
    processes:
      - Qt Creator
    options:
      - name: Copy QT
        action: press ctrl+c
        color: 0xffff00
      - name: Cut QT
        action: press ctrl+x
        color: 0xff0000
      - name: Paste QT
        action: press ctrl+v
        color: 0x00ff00